### ISSUE TITLE
Error running script in Azure Cloud Shell: Deployment template validation failed: The template variable 'deploymentUrl' is not valid: The language expression property 'templateLink' doesn't exist

### ISSUE THREAD

**Issue by andrewdove** [MicrosoftDocs/mslearn-distribute-load-with-traffic-manager#10]
From the Azure Traffic Manager Exercises here:
[https://docs.microsoft.com/en-us/learn/modules/distribute-load-with-traffic-manager/3-exercise-priority-routing]
Having first run step(1):

az network traffic-manager profile create \
    --resource-group learn-7a671ff5-832d-4f29-91b7-d462bad90e50 \
    --name TM-MusicStream-Priority \
    --routing-method Priority \
    --unique-dns-name TM-MusicStream-Priority-$RANDOM

Running step (2) :

az deployment group create \
    --resource-group learn-7a671ff5-832d-4f29-91b7-d462bad90e50 \
    --template-uri  https://raw.githubusercontent.com/MicrosoftDocs/mslearn-distribute-load-with-traffic-manager/master/azuredeploy.json \
    --parameters password="$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 32)"

Produces the fatal error: {'additionalProperties': {}, 'code': 'InvalidTemplate', 'message': "Deployment template validation failed: 'The template variable 'deploymentUrl' is not valid: The language expression property 'templateLink' doesn't exist, available properties are 'template, templateHash, parameters, mode, provisioningState'.. Please see https://aka.ms/arm-template-expressions for usage details.'.", 'target': None, 'details': None, 'additionalInfo': [{'additionalProperties': {}, 'type': 'TemplateViolation', 'info': {'lineNumber': 14, 'linePosition': 69, 'path': 'properties.template.variables.deploymentUrl'}}]}

**Comment by stevensnicole** [comment]
Looks to be linked to https://github.com/Azure/azure-cli/issues/12890

**Comment by jaydarius** [comment]
Thanks @stevensnicole - worked for me!
Though one thing: the  "deploymentUrl" line must also be removed (for us newbies ^_^).

**Comment by stevensnicole** [comment]
Hey Jay,

Sorry good point, it's already deleted in my github repo, I forgot to add
it in the instructions :)

Good luck with your learning!

**Comment by pauldj54** [comment]
Thanks a lot @stevensnicole and @jaydarius this helped me continue with my learning path, maybe for us the most newbies:
- Navigate to the original repo and fork it
- Clone it to your local machine
- Make the proposed changes
- Commit and push
- Reference the adjusted template from your repo

An easy way, just use the repo from stevensnicole:
`az deployment group create \
    --resource-group learn-7b791aee-e424-4eb5-b4b0-5add17b7dae2 \
    --template-uri  https://raw.githubusercontent.com/stevensnicole/mslearn-distribute-load-with-traffic-manager/master/azuredeploy.json \
    --parameters password="$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 32)"` 

Regards, 
Paul

**Comment by prudent-rohit** [comment]
I'm lazy - just used Paul's repo instead :-)
Thanks Paul

**Comment by stwilson74** [comment]
Thanks @pauldj54 and @stevensnicole I am still seeing the error but this got me through the exercise relatively painlessly.

**Comment by jboeshart** [comment]
Hi all, thanks for reporting this issue. It is related to the defect that was linked above. That's since been fixed in the CLI but hasn't rolled out to cloud shell just yet. That should happen through next week. In the meantime I've updated the template to have the URL hardcoded. Will back that out once the cloud shell is running the latest version of the CLI.

#12
